// Wilderness areas data for the Trip Planner page.
// permitType: 'quota' | 'lottery' | 'first-come' | 'self-issue'
// reservationOpens: human-readable date string, or null for walk-up only
// recGovId: Recreation.gov permit ID (links directly to booking), or null

export const AREAS = [
  // ─── California ───────────────────────────────────────────────────────────

  {
    id: 'john-muir-wilderness',
    name: 'John Muir Wilderness',
    state: 'CA',
    region: 'Sierra Nevada',
    managing: 'Inyo & Sierra National Forests',
    permitType: 'quota',
    season: { start: 'May 1', end: 'Nov 1' },
    reservationOpens: 'April 1',
    bookingHorizon: '6 months ahead (rolling)',
    dailyQuota: 'Varies by trailhead',
    recGovId: '445856',
    tags: ['sierra', 'overnight', 'popular', 'jmt'],
    notes:
      'Covers the eastern Sierra from Mono County south to Sequoia. Many trailheads require a permit — check specific entry point quotas. JMT thru-hikers use a separate permit.',
  },
  {
    id: 'desolation-wilderness',
    name: 'Desolation Wilderness',
    state: 'CA',
    region: 'Sierra Nevada',
    managing: 'Eldorado National Forest',
    permitType: 'quota',
    season: { start: 'May 15', end: 'Sep 30' },
    reservationOpens: 'March 1',
    bookingHorizon: 'Up to 6 months ahead',
    dailyQuota: 'Varies by trailhead',
    recGovId: '233261',
    tags: ['sierra', 'overnight', 'lake tahoe', 'popular'],
    notes:
      'One of the most heavily used wilderness areas in the US. Weekend permits sell out quickly. Day-use requires a self-issued free permit.',
  },
  {
    id: 'ansel-adams-wilderness',
    name: 'Ansel Adams Wilderness',
    state: 'CA',
    region: 'Sierra Nevada',
    managing: 'Inyo & Sierra National Forests',
    permitType: 'quota',
    season: { start: 'June 1', end: 'Oct 31' },
    reservationOpens: 'April 1',
    bookingHorizon: '6 months ahead (rolling)',
    dailyQuota: 'Varies by trailhead',
    recGovId: '233267',
    tags: ['sierra', 'overnight', 'popular'],
    notes:
      'Borders Yosemite NP to the south. Popular trailheads include Agnew Meadows, Mammoth Lakes Basin, and Reds Meadow. Shared quota system with JMW at some entry points.',
  },
  {
    id: 'hoover-wilderness',
    name: 'Hoover Wilderness',
    state: 'CA',
    region: 'Sierra Nevada',
    managing: 'Humboldt-Toiyabe & Inyo National Forests',
    permitType: 'self-issue',
    season: { start: 'June 15', end: 'Oct 15' },
    reservationOpens: null,
    bookingHorizon: null,
    dailyQuota: null,
    recGovId: null,
    tags: ['sierra', 'overnight', 'walk-up'],
    notes:
      'Walk-up, self-issued permits at trailheads — no reservation required. Quieter alternative to the crowded eastern Sierra permits. Twin Lakes and Green Creek are popular entry points.',
  },
  {
    id: 'emigrant-wilderness',
    name: 'Emigrant Wilderness',
    state: 'CA',
    region: 'Sierra Nevada',
    managing: 'Stanislaus National Forest',
    permitType: 'self-issue',
    season: { start: 'June 1', end: 'Oct 31' },
    reservationOpens: null,
    bookingHorizon: null,
    dailyQuota: null,
    recGovId: null,
    tags: ['sierra', 'overnight', 'walk-up', 'uncrowded'],
    notes:
      'No quota, no advance permit required — just self-issue at the trailhead. One of the last permit-free wilderness areas in the northern Sierra. Great alternative to overcrowded Yosemite.',
  },
  {
    id: 'dinkey-lakes-wilderness',
    name: 'Dinkey Lakes Wilderness',
    state: 'CA',
    region: 'Sierra Nevada',
    managing: 'Sierra National Forest',
    permitType: 'self-issue',
    season: { start: 'June 1', end: 'Oct 15' },
    reservationOpens: null,
    bookingHorizon: null,
    dailyQuota: null,
    recGovId: null,
    tags: ['sierra', 'overnight', 'walk-up', 'uncrowded'],
    notes:
      'Small, relatively uncrowded wilderness south of Yosemite. Self-issue permit at trailhead. Good fishing lakes and granite scenery without the competition for permits.',
  },
  {
    id: 'yosemite-wilderness',
    name: 'Yosemite Wilderness',
    state: 'CA',
    region: 'Sierra Nevada',
    managing: 'Yosemite National Park (NPS)',
    permitType: 'quota',
    season: { start: 'May 1', end: 'Oct 31' },
    reservationOpens: 'March 1',
    bookingHorizon: 'Up to 24 weeks ahead',
    dailyQuota: 'Varies by trailhead (40–60% reservable)',
    recGovId: '445858',
    tags: ['sierra', 'overnight', 'popular', 'nps'],
    notes:
      'Wilderness permits required for all overnight stays. 60% of daily quota is reservable starting March 1; remaining 40% released as walk-up permits at 11am the day before entry. Half Dome cables require a separate permit. Walk-up competition at Valley trailheads is intense in summer.',
  },
  {
    id: 'point-reyes-seashore',
    name: 'Point Reyes National Seashore',
    state: 'CA',
    region: 'Bay Area / Coast',
    managing: 'Point Reyes National Seashore (NPS)',
    permitType: 'quota',
    season: { start: 'Year-round', end: null },
    reservationOpens: 'Rolling — up to 6 months ahead',
    bookingHorizon: 'Up to 6 months ahead',
    dailyQuota: 'Varies by campsite (12 sites total)',
    recGovId: '445594',
    tags: ['coast', 'overnight', 'year-round', 'nps', 'backpacking'],
    notes:
      'Four hike-in campgrounds: Coast, Sky, Glen, and Wildcat. Permits required for all overnight stays, reservable up to 6 months out. Coastal weather is unpredictable — fog and wind common even in summer. Tule elk, bobcats, and dramatic cliffs are the draw.',
  },
  {
    id: 'lassen-volcanic-backcountry',
    name: 'Lassen Volcanic National Park',
    state: 'CA',
    region: 'Northern California',
    managing: 'Lassen Volcanic National Park (NPS)',
    permitType: 'self-issue',
    season: { start: 'July 1', end: 'Sep 30' },
    reservationOpens: null,
    bookingHorizon: null,
    dailyQuota: null,
    recGovId: null,
    tags: ['volcanic', 'overnight', 'walk-up', 'nps', 'uncrowded'],
    notes:
      'Backcountry permits are free and self-issued at the Lassen Park Visitor Center or Kohm Yah-mah-nee Visitor Center. No online reservation system — walk-up only. Volcanic features, hydrothermal areas, and high alpine lakes. Snow can persist into July.',
  },

  // ─── Pacific Northwest ─────────────────────────────────────────────────────

  {
    id: 'enchantments',
    name: 'The Enchantments (Alpine Lakes Wilderness)',
    state: 'WA',
    region: 'Pacific Northwest',
    managing: 'Okanogan-Wenatchee National Forest',
    permitType: 'lottery',
    season: { start: 'June 15', end: 'Oct 31' },
    reservationOpens: 'Feb 1 (lottery application window)',
    bookingHorizon: 'Lottery results announced ~April 1',
    dailyQuota: '~50 overnight (core zone)',
    recGovId: '233273',
    tags: ['pnw', 'overnight', 'popular', 'lottery', 'alpine'],
    notes:
      'One of the most competitive permits in the country. Enter the lottery Feb 1–Mar 1 on Recreation.gov. Walk-up permits available daily at 7:45am at the Leavenworth ranger station — lines form before dawn in peak season. Core zone (Enchantment Lakes Basin) is the hardest to get.',
  },
  {
    id: 'central-cascades',
    name: 'Central Cascades Wilderness',
    state: 'WA',
    region: 'Pacific Northwest',
    managing: 'Mt. Baker-Snoqualmie & Okanogan-Wenatchee National Forests',
    permitType: 'quota',
    season: { start: 'May 25', end: 'Oct 31' },
    reservationOpens: 'March 1',
    bookingHorizon: 'Up to 6 months ahead',
    dailyQuota: 'Varies by trailhead',
    recGovId: '4675311',
    tags: ['pnw', 'overnight', 'popular', 'day-use'],
    notes:
      'Covers popular trailheads including Ira Spring, Snow Lake, and Pratt Lake. Both day-use and overnight permits are required for quota trailheads. Day permits are often easier to get than overnight.',
  },
  {
    id: 'three-sisters-wilderness',
    name: 'Three Sisters Wilderness',
    state: 'OR',
    region: 'Pacific Northwest',
    managing: 'Deschutes & Willamette National Forests',
    permitType: 'quota',
    season: { start: 'May 15', end: 'Oct 31' },
    reservationOpens: 'April 1',
    bookingHorizon: 'Up to 6 months ahead',
    dailyQuota: 'Varies by trailhead',
    recGovId: '4675334',
    tags: ['pnw', 'overnight', 'oregon', 'popular'],
    notes:
      'Some of the most sought-after trails in Oregon. South Sister summit, Broken Top, and Green Lakes are peak-demand trailheads. Reservations required May 25–Oct 15 at quota trailheads.',
  },
  {
    id: 'glacier-peak-wilderness',
    name: 'Glacier Peak Wilderness',
    state: 'WA',
    region: 'Pacific Northwest',
    managing: 'Mt. Baker-Snoqualmie & Okanogan-Wenatchee National Forests',
    permitType: 'self-issue',
    season: { start: 'July 1', end: 'Sep 30' },
    reservationOpens: null,
    bookingHorizon: null,
    dailyQuota: null,
    recGovId: null,
    tags: ['pnw', 'overnight', 'walk-up', 'remote', 'uncrowded'],
    notes:
      'No permit reservation required — self-issue at trailheads. One of the most remote and rugged wilderness areas in the lower 48. Most trails require significant miles of approach. Popular for Glacier Peak summit attempts.',
  },

  // ─── Colorado ─────────────────────────────────────────────────────────────

  {
    id: 'indian-peaks-wilderness',
    name: 'Indian Peaks Wilderness',
    state: 'CO',
    region: 'Rocky Mountains',
    managing: 'Arapaho & Roosevelt National Forests / Rocky Mountain NP',
    permitType: 'quota',
    season: { start: 'June 1', end: 'Sep 15' },
    reservationOpens: 'April 1',
    bookingHorizon: 'Up to 6 months ahead',
    dailyQuota: 'Varies by zone',
    recGovId: '233388',
    tags: ['colorado', 'overnight', 'rockies', 'popular'],
    notes:
      'Overnight permits required Jun 1–Sep 15, Fri–Sun and holidays. Free self-issue permits available Mon–Thu. Very popular due to proximity to Denver/Boulder metro. Permits go fast on release day.',
  },
  {
    id: 'maroon-bells-snowmass',
    name: 'Maroon Bells–Snowmass Wilderness',
    state: 'CO',
    region: 'Rocky Mountains',
    managing: 'White River National Forest',
    permitType: 'quota',
    season: { start: 'June 15', end: 'Oct 1' },
    reservationOpens: 'April 1',
    bookingHorizon: 'Up to 6 months ahead',
    dailyQuota: 'Varies by trailhead',
    recGovId: '445860',
    tags: ['colorado', 'overnight', 'rockies', 'popular', 'iconic'],
    notes:
      'Home to the famous Maroon Bells — among the most photographed mountains in Colorado. Day-use vehicles restricted in summer; shuttle required. The four 14ers here draw huge crowds. Crater Lake and West Maroon Pass are popular overnight routes.',
  },
  {
    id: 'weminuche-wilderness',
    name: 'Weminuche Wilderness',
    state: 'CO',
    region: 'Rocky Mountains',
    managing: 'San Juan & Rio Grande National Forests',
    permitType: 'self-issue',
    season: { start: 'June 1', end: 'Sep 30' },
    reservationOpens: null,
    bookingHorizon: null,
    dailyQuota: null,
    recGovId: null,
    tags: ['colorado', 'overnight', 'walk-up', 'remote', 'uncrowded'],
    notes:
      "Colorado's largest wilderness area. No permit required — self-issue at trailheads. The Weminuche features the iconic Needle Mountains and Chicago Basin (accessible via Durango & Silverton Narrow Gauge Railroad). Camping within 100' of water or trails in some zones.",
  },

  // ─── Southwest ────────────────────────────────────────────────────────────

  {
    id: 'grand-canyon-backcountry',
    name: 'Grand Canyon Backcountry',
    state: 'AZ',
    region: 'Southwest',
    managing: 'Grand Canyon National Park (NPS)',
    permitType: 'lottery',
    season: { start: 'Year-round', end: null },
    reservationOpens: 'Oct 1 (lottery for following spring); rolling 4 months ahead',
    bookingHorizon: '4 months ahead (rolling after lottery)',
    dailyQuota: 'Varies by corridor and zone',
    recGovId: null,
    tags: ['arizona', 'overnight', 'nps', 'lottery', 'popular', 'iconic'],
    notes:
      'Backcountry Office manages permits separately from Recreation.gov. Apply by mail/fax/in-person starting Oct 1 for the following spring. Rolling availability opens 4 months ahead for remaining spots. Bright Angel, South Kaibab, and North Kaibab corridors are most popular. Heat is a serious hazard May–Sep.',
  },
  {
    id: 'zion-narrows',
    name: 'Zion Narrows (Top-Down)',
    state: 'UT',
    region: 'Southwest',
    managing: 'Zion National Park (NPS)',
    permitType: 'lottery',
    season: { start: 'Apr 1', end: 'Oct 31' },
    reservationOpens: 'Feb 1 (lottery for Apr–Jun); rolling 3 months ahead',
    bookingHorizon: '3 months ahead (rolling)',
    dailyQuota: '80 people per day (top-down)',
    recGovId: '445860',
    tags: ['utah', 'overnight', 'nps', 'popular', 'slot canyon'],
    notes:
      'Top-down through-hike of the Virgin River requires overnight permit. Bottom-up day hike needs no permit. Flash flood risk is real — check forecasts before entering. Wetsuit rental recommended in spring/fall. Lottery for peak dates; rolling reservations for others.',
  },
  {
    id: 'havasupai',
    name: 'Havasupai (Havasu Falls)',
    state: 'AZ',
    region: 'Southwest',
    managing: 'Havasupai Tribe',
    permitType: 'lottery',
    season: { start: 'Feb 1', end: 'Nov 30' },
    reservationOpens: 'Feb 1 (annual lottery)',
    bookingHorizon: 'Lottery results released ~Feb/March',
    dailyQuota: '~300 overnight visitors',
    recGovId: null,
    tags: ['arizona', 'overnight', 'tribal', 'lottery', 'iconic', 'waterfall'],
    notes:
      'Permits managed by the Havasupai Tribe — NOT through Recreation.gov. Apply at havasupairesortations.com starting Feb 1. Demand massively exceeds supply. The 10-mile hike to Supai Village drops 2,000 feet. Helicopter and mule options available. Permits include camping fee.',
  },

  // ─── Other ────────────────────────────────────────────────────────────────

  {
    id: 'boundary-waters',
    name: 'Boundary Waters Canoe Area (BWCA)',
    state: 'MN',
    region: 'Midwest',
    managing: 'Superior National Forest',
    permitType: 'quota',
    season: { start: 'May 1', end: 'Sep 30' },
    reservationOpens: 'Jan 1',
    bookingHorizon: 'Up to the trip date',
    dailyQuota: 'Varies by entry point (~18 per day at popular points)',
    recGovId: '233396',
    tags: ['minnesota', 'canoe', 'overnight', 'popular', 'paddle'],
    notes:
      'Entry point permits required May 1–Sep 30. Jan 1 is the busiest booking day — popular entry points like Moose Lake and Sawbill fill within minutes. Motor quota areas have separate limits. Self-issued permits available for shoulder season (Oct–Apr).',
  },
  {
    id: 'bob-marshall-wilderness',
    name: 'Bob Marshall Wilderness Complex',
    state: 'MT',
    region: 'Northern Rockies',
    managing: 'Flathead & Lewis & Clark National Forests',
    permitType: 'self-issue',
    season: { start: 'June 15', end: 'Sep 30' },
    reservationOpens: null,
    bookingHorizon: null,
    dailyQuota: null,
    recGovId: null,
    tags: ['montana', 'overnight', 'walk-up', 'remote', 'uncrowded', 'grizzly'],
    notes:
      'No permit required — self-issue at trailheads. One of the most intact ecosystems in the lower 48, with grizzly bears, wolves, and elk. The Chinese Wall escarpment is iconic. Outfitter/guide density is high in September during hunting season.',
  },
]

export const STATES = [...new Set(AREAS.map((a) => a.state))].sort()
export const REGIONS = [...new Set(AREAS.map((a) => a.region))].sort()

export const PERMIT_TYPE_LABELS = {
  quota: 'Quota',
  lottery: 'Lottery',
  'first-come': 'First Come',
  'self-issue': 'Walk-up / Self-Issue',
}
